"""Single-URL workflow page built on the shared Open-Flame design system."""

WORKFLOW_HTML = r'''<!doctype html>
<html lang="zh-CN" class="no-js" data-theme="system">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <title>Open-Flame · 自动流程</title>
  <link rel="stylesheet" href="/assets/open-flame.css">
  <script src="/assets/open-flame-shell.js" defer></script>
</head>
<body class="workflow-page">
  <header class="topbar-shell"><div class="topbar">
    <a class="brand" href="/" aria-label="Open-Flame 下载首页"><span class="brand-mark" aria-hidden="true">OF</span><span>Open-Flame</span></a>
    <nav class="primary-nav" aria-label="主要功能"><a class="nav-link" href="/">下载</a><a class="nav-link" href="/edits">编辑</a><a class="nav-link" href="/uploads">上传</a><a class="nav-link" href="/workflows" aria-current="page">自动流程</a></nav>
    <label class="theme-control"><span>外观</span><select data-of-theme aria-label="界面外观"><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label>
  </div></header>
  <main class="of-shell">
    <header class="page-header"><p class="eyebrow">URL 到三平台的可恢复编排</p><h1>一次设置，自动推进每个阶段</h1><p class="lede">输入一个网址，按已保存的编辑与投稿参数完成下载、翻译、配音、封面和上传。每个跨域副本都会校验，重启后从持久状态继续。</p><p class="notice page-note">云端 AI 会在单独勾选数据外发授权后启动；自动确认只适用于本次流程，应用重启或重试后仍会再次停下。平台返回 submitted 只代表提交完成；公开、审核与定时发布结果仍以平台后台为准。</p></header>
    <section class="status-strip" aria-label="自动流程摘要"><div class="status-tile"><p class="status-label">核心</p><p class="status-value">轻量状态机</p></div><div class="status-tile"><p class="status-label">AI</p><p class="status-value">独立运行时</p></div><div class="status-tile"><p class="status-label">发布</p><p class="status-value">Bilibili · 抖音 · 视频号</p></div></section>
    <p id="message" role="status" aria-live="polite">正在连接自动流程…</p>
    <section class="card primary-card" aria-labelledby="create-heading"><div class="card-header"><div><p class="section-index">新建流程</p><h2 id="create-heading">来源、处理与投稿参数</h2><p class="muted">所有参数会形成不可变快照；同一请求键重放不会创建第二条流程。</p></div><button id="refresh" class="secondary" type="button">刷新</button></div>
      <form id="workflow-form">
        <label for="source-url">视频网址</label><input id="source-url" type="url" maxlength="4096" required placeholder="https://…">
        <label for="workflow-name">流程名称</label><input id="workflow-name" maxlength="160" required value="自动翻译配音发布">
        <label for="credential-mode">下载登录方式</label><select id="credential-mode"><option value="use_default">使用已配置的默认登录</option><option value="anonymous">匿名下载</option></select>
        <fieldset><legend>编辑与 AI</legend>
          <div class="diagnostic-grid"><div class="diagnostic-panel"><h3>分段与封面</h3><label class="choice"><input id="segment-enabled" type="checkbox" checked><span>生成一个视频分段</span></label><label for="segment-start">开始（秒）</label><input id="segment-start" type="number" min="0" step="0.001" value="0"><label for="segment-end">结束（秒）</label><input id="segment-end" type="number" min="0.1" step="0.001" value="60"><label class="choice"><input id="cover-enabled" type="checkbox" checked><span>在 0 秒生成封面</span></label><label for="cover-ratio">封面比例</label><select id="cover-ratio"><option value="4:3">4:3 横版</option><option value="3:4">3:4 竖版</option><option value="16:9">16:9 横版</option><option value="9:16">9:16 竖版</option><option value="1:1">1:1 方形</option></select></div>
          <div class="diagnostic-panel"><h3>翻译与配音</h3><p id="ai-help" class="muted small">正在读取隔离 AI runtime…</p><label class="choice"><input id="translation-enabled" type="checkbox"><span>自动听写并翻译</span></label><label for="transcription-engine">听写模型</label><select id="transcription-engine" disabled><option value="">尚无可用模型</option></select><label for="translation-engine">翻译模型</label><select id="translation-engine" disabled><option value="">尚无可用模型</option></select><label for="target-language">目标语言</label><select id="target-language"><option value="zh-CN">中文</option><option value="en">English</option></select><label class="choice"><input id="dubbing-enabled" type="checkbox"><span>使用标准音色自动配音</span></label><label for="speech-engine">配音模型</label><select id="speech-engine" disabled><option value="">尚无可用模型</option></select><label for="voice-id">标准音色</label><select id="voice-id" disabled><option value="">尚无可用标准音色</option></select><label class="choice"><input id="replace-audio" type="checkbox"><span>替换原声；未勾选时把原声压低到 22% 后叠加配音</span></label><p id="ai-egress-summary" class="notice small">启用 AI 后会在这里显示外发范围。</p><label class="choice"><input id="ai-egress" type="checkbox" disabled><span>我确认将所选音频片段与文字发送给所选云端 AI；调用可能产生费用</span></label></div></div>
        </fieldset>
        <fieldset><legend>上传账号与内容</legend><p id="account-help" class="muted small">正在读取已连接账号…</p><div id="accounts"></div><label for="title">标题</label><input id="title" maxlength="100" required><label for="description">简介</label><textarea id="description" maxlength="2000"></textarea><label for="tags">标签（逗号分隔）</label><input id="tags" maxlength="220"><label for="category-id">Bilibili 分区 ID</label><input id="category-id" type="number" min="1" max="10000"><label for="copyright">Bilibili 来源</label><select id="copyright"><option value="1">原创</option><option value="2">转载</option></select><label for="source-credit">转载来源（原创时留空）</label><input id="source-credit" maxlength="200"><label for="mode">执行方式</label><select id="mode"><option value="publish">投稿发布</option><option value="draft">保存平台草稿</option></select><label for="publish-at">定时发布时间（可选）</label><input id="publish-at" type="datetime-local"><label for="short-title">视频号短标题（7–15 字，可选）</label><input id="short-title" minlength="7" maxlength="15"><label class="choice"><input id="ai-label" type="checkbox" checked><span>标记含 AI 生成内容</span></label></fieldset>
        <fieldset><legend>自动确认</legend><label class="choice"><input id="auto-edit" type="checkbox" checked><span>创建流程时预先授权自动开始编辑与 AI 处理</span></label><label class="choice"><input id="auto-upload" type="checkbox"><span>创建流程时预先授权所选账号自动投稿</span></label><p class="muted small">不勾选时，流程会停在核对节点，可在下方确认。未知结果永远停下，不自动重试。</p></fieldset>
        <button type="submit">创建并开始自动流程</button>
      </form>
    </section>
    <section class="card" aria-labelledby="records-heading"><div class="card-header"><div><p class="section-index">持续状态</p><h2 id="records-heading">流程记录</h2><p class="muted">页面轮询只刷新记录，不改动上方输入。</p></div></div><div id="workflows"><p class="muted">尚无流程。</p></div></section>
    <p class="page-footer">Open-Flame 0.28.0 · 自动流程使用独立 Workflow Schema 1</p>
  </main>
  <script>
'use strict';
const $=id=>document.getElementById(id);let csrf='',busy=false,pollTimer=null,accounts=[],aiCapabilities=[];
const stateNames={created:'已创建',downloading:'下载中',preparing_edit:'准备编辑',awaiting_ai_review:'等待 AI 结果核对',awaiting_edit_confirmation:'等待编辑确认',rendering:'编辑处理中',preparing_upload:'准备上传草稿',awaiting_upload_confirmation:'等待上传确认',uploading:'上传中',completed:'已完成提交',attention_required:'需要处理',canceled:'已取消'};
const codeNames={download_multiple_assets:'下载产生多个视频，请手动选择',edit_multiple_outputs:'编辑产生多个视频，请手动选择',upload_unknown:'平台结果未知，请到后台核对',ai_runtime_missing:'AI 运行时未安装',ai_runtime_invalid:'AI 运行时校验失败',ai_provider_auth_missing:'AI provider 凭据未配置',ai_transcription_confirmation_required:'请确认开始自动听写',ai_transcription_review_required:'请核对并批准听写时间轴',ai_translation_confirmation_required:'请确认开始自动翻译',ai_translation_review_required:'请核对并批准翻译时间轴',ai_restart_confirmation_required:'应用已重启，请重新确认当前 AI 步骤',ai_retry_confirmation_required:'已创建 AI 重试任务，请明确确认后再执行',restart_confirmation_required:'应用已重启，请重新确认编辑',edit_restart_confirmation_required:'应用已重启，请重新确认编辑',render_retry_confirmation_required:'已创建新的编辑计划，请确认重试',upload_restart_confirmation_required:'应用已重启，请重新确认投稿',upload_retry_confirmation_required:'已找到上传重试任务，请明确确认后再投稿',account_session_changed:'所选上传账号的登录会话已变化，请重建流程',ai_speech_timing_overflow:'部分配音超过字幕时间槽，请到编辑页调整文本或音色',ai_timeline_segment_empty:'所选分段内没有已批准的字幕内容',processor_not_configured:'FFmpeg 工具尚未就绪',workflow_domain_failed:'流程步骤执行失败'};
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('danger',error);}
const pendingKeys=new Map();
function key(prefix){return prefix+'-'+crypto.randomUUID();}
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object'){const output={};for(const name of Object.keys(value).sort())output[name]=canonical(value[name]);return output;}return value;}
async function intentDigest(value){const bytes=new TextEncoder().encode(JSON.stringify(canonical(value)));if(crypto.subtle){const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(item=>item.toString(16).padStart(2,'0')).join('');}let hash=2166136261;for(const byte of bytes){hash^=byte;hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,'0')+'-'+bytes.length;}
async function pendingWorkflowKey(intent){const storageKey='open-flame-workflow-pending-'+await intentDigest(intent);let requestKey='';try{requestKey=sessionStorage.getItem(storageKey)||pendingKeys.get(storageKey)||'';}catch{requestKey=pendingKeys.get(storageKey)||'';}if(!/^workflow-[0-9a-f-]{36}$/.test(requestKey)){requestKey=key('workflow');try{sessionStorage.setItem(storageKey,requestKey);pendingKeys.delete(storageKey);}catch{pendingKeys.set(storageKey,requestKey);}}return {requestKey,storageKey};}
async function api(path,options={}){const headers=new Headers(options.headers||{});if(options.method&&options.method!=='GET')headers.set('X-Workflow-CSRF',csrf);if(options.body)headers.set('Content-Type','application/json');const response=await fetch('/api/v1/workflows'+path,{...options,headers});let data=null;try{data=await response.json();}catch{}if(!response.ok)throw new Error(data?.detail||'request_failed');return data;}
function el(tag,text,className=''){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
function selectedAccounts(){return [...document.querySelectorAll('[data-account]:checked')].map(node=>node.value);}
function renderAccounts(){const host=$('accounts');host.replaceChildren();const ready=accounts.filter(item=>item.lifecycle_state!=='disconnected'&&item.auth_state==='ready');for(const account of ready){const label=el('label',undefined,'choice'),input=document.createElement('input');input.type='checkbox';input.value=account.id;input.dataset.account='';label.append(input,el('span',(account.name||'未命名')+' · '+({bilibili:'Bilibili',douyin:'抖音',tencent:'视频号'}[account.platform]||account.platform)));host.append(label);}if(!ready.length)host.append(el('p','没有 ready 上传账号；请先到上传页扫码登录。','notice'));$('account-help').textContent=ready.length?'选择本次流程使用的账号。':'需要先连接账号。';}
function selectedEngine(id){const value=$(id).value;if(!value)throw new Error('所选 AI 能力不可用');let parsed;try{parsed=JSON.parse(value);}catch{throw new Error('所选 AI 能力不可用');}if(!Array.isArray(parsed)||parsed.length!==2||!parsed.every(item=>typeof item==='string'&&item))throw new Error('所选 AI 能力不可用');return {provider:parsed[0],model:parsed[1]};}
function selectedCapability(id,operation){let engine=null;try{engine=JSON.parse($(id).value);}catch{}return Array.isArray(engine)?aiCapabilities.find(item=>item.operation===operation&&item.provider_id===engine[0]&&item.model_id===engine[1]):null;}
function renderAiEgress(){const enabled=$('translation-enabled').checked&&$('dubbing-enabled').checked,consent=$('ai-egress');consent.disabled=!enabled;if(!enabled){consent.checked=false;$('ai-egress-summary').textContent='AI 默认关闭；启用听写、翻译和配音后再核对数据范围。';return;}const transcribe=selectedCapability('transcription-engine','transcribe'),translate=selectedCapability('translation-engine','translate'),dub=selectedCapability('speech-engine','dub');const remote=[transcribe,translate,dub].some(item=>item?.execution==='remote');const range=$('segment-enabled').checked?$('segment-start').value+'–'+$('segment-end').value+' 秒':'完整视频（最长 90 分钟）';const declared=[transcribe,translate,dub].flatMap(item=>Array.isArray(item?.data_egress)?item.data_egress:[]);const scope=[...new Set(declared)].join('、')||'未声明';$('ai-egress-summary').textContent=remote?'听写发送 '+range+' 的派生单声道音频；翻译发送听写文字；配音发送译文。Provider 声明范围：'+scope+'。真实调用可能产生费用。':'所选能力均在隔离本地 runtime 中执行，不外发媒体或文字。';}
function renderVoiceOptions(){const select=$('voice-id'),prior=select.value;select.replaceChildren();const capability=selectedCapability('speech-engine','dub');const voices=Array.isArray(capability?.voices)?capability.voices.filter(item=>item&&typeof item.id==='string'&&item.id&&item.is_clone!==true):[];for(const voice of voices){const option=document.createElement('option');option.value=voice.id;option.textContent=voice.label||voice.id;select.append(option);}select.disabled=!voices.length;if(prior&&[...select.options].some(option=>option.value===prior))select.value=prior;else if([...select.options].some(option=>option.value==='marin'))select.value='marin';if(!voices.length){const option=document.createElement('option');option.value='';option.textContent='尚无可用标准音色';select.append(option);}renderAiEgress();}
function renderAiEngines(){const specs=[['transcription-engine','transcribe','听写'],['translation-engine','translate','翻译'],['speech-engine','dub','配音']];let available=0;for(const [id,operation,label] of specs){const select=$(id),prior=select.value,rows=aiCapabilities.filter(item=>item.operation===operation&&['ready','unverified'].includes(item.status)&&typeof item.provider_id==='string'&&typeof item.model_id==='string');if(operation==='transcribe')rows.sort((left,right)=>Number(right.model_id==='whisper-1')-Number(left.model_id==='whisper-1'));select.replaceChildren();for(const row of rows){const option=document.createElement('option');option.value=JSON.stringify([row.provider_id,row.model_id]);option.textContent=row.provider_id+' · '+row.model_id+(row.execution==='remote'?' · 云端':' · 本地');select.append(option);}select.disabled=!rows.length;if(prior&&[...select.options].some(option=>option.value===prior))select.value=prior;if(rows.length)available++;else{const option=document.createElement('option');option.value='';option.textContent='尚无可用'+label+'模型';select.append(option);}}renderVoiceOptions();const authBlocked=specs.every(([,operation])=>aiCapabilities.some(item=>item.operation===operation&&item.status==='blocked'&&item.reason_code==='ai_provider_auth_missing'));$('ai-help').textContent=available===3?'AI runtime 完整性已校验；首次真实调用仍可能受凭据、费用或网络影响。':authBlocked?'AI runtime 完整性已校验；请配置 provider 凭据并重启应用后再启用云端 AI。':'请先安装并配置同时支持听写、翻译和标准音色的隔离 AI runtime。';}
function recipe(){const segments=[];if($('segment-enabled').checked){const start=Math.round(Number($('segment-start').value)*1000),end=Math.round(Number($('segment-end').value)*1000);if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<=start)throw new Error('分段时间无效');segments.push({start_ms:start,end_ms:end,label:'主视频'});}const cover=$('cover-enabled').checked?{timestamp_ms:0,aspect_ratio:$('cover-ratio').value,title:$('title').value.trim(),subtitle:''}:null;const translate=$('translation-enabled').checked,target=$('target-language').value,dub=$('dubbing-enabled').checked;if(dub&&!translate)throw new Error('自动配音需要同时启用听写与翻译');if(translate&&!dub)throw new Error('自动流程中的译文必须配音后才能进入上传；只导出字幕请使用编辑页');if(!dub&&segments.length!==1)throw new Error('未启用配音时必须选择一个上传分段');if(!segments.length&&!cover&&!translate)throw new Error('请至少启用一种处理');const translationEngine=translate?selectedEngine('translation-engine'):null,speechEngine=dub?selectedEngine('speech-engine'):null,voice=dub?$('voice-id').value:'';if(dub&&!voice)throw new Error('没有可用的标准音色');return {segments,cover,translation:translate?{enabled:true,source_language:'auto',target_language:target,provider:translationEngine.provider,model:translationEngine.model,state:'needs_review'}:null,dubbing:dub?{enabled:true,language:target,provider:speechEngine.provider,model:speechEngine.model,voice,state:'needs_review',replace_original_audio:$('replace-audio').checked}:null};}
function textLength(value){return [...value].length;}
function localDateTimeKey(value){const pad=number=>String(number).padStart(2,'0');return value.getFullYear()+'-'+pad(value.getMonth()+1)+'-'+pad(value.getDate())+'T'+pad(value.getHours())+':'+pad(value.getMinutes());}
function scheduleFor(platform,raw){if(!raw)return {publish_at_unix:null,publish_timezone_offset_minutes:null};const parsed=new Date(raw),key=raw.slice(0,16);if(Number.isNaN(parsed.getTime())||localDateTimeKey(parsed)!==key)throw new Error('定时发布时间无效，可能落在本地夏令时跳时区间');for(let minutes=-180;minutes<=180;minutes+=30){if(!minutes)continue;const alternate=new Date(parsed.getTime()+minutes*60000);if(localDateTimeKey(alternate)===key&&alternate.getTimezoneOffset()!==parsed.getTimezoneOffset())throw new Error('该本地时间在夏令时切换时出现两次，请选择其他时间');}const lead=platform==='bilibili'?21900000:14700000;if(parsed.getTime()<=Date.now()+lead)throw new Error((platform==='bilibili'?'Bilibili':platform==='douyin'?'抖音':'视频号')+' 定时发布至少需提前 '+(platform==='bilibili'?'6 小时 5 分钟':'4 小时 5 分钟'));if(platform==='tencent'&&parsed.getMinutes()!==0)throw new Error('视频号定时发布只支持整点');if(platform==='tencent'&&parsed.getTime()>Date.now()+28*24*3600000)throw new Error('视频号定时发布最多可提前 28 天');return {publish_at_unix:Math.floor(parsed.getTime()/60000)*60,publish_timezone_offset_minutes:-parsed.getTimezoneOffset()};}
function upload(){const ids=selectedAccounts();if(!ids.length)throw new Error('请选择至少一个 ready 上传账号');const selected=ids.map(id=>accounts.find(item=>item.id===id));if(selected.some(item=>!item||item.lifecycle_state==='disconnected'||item.auth_state!=='ready'))throw new Error('所选账号状态已变化，请刷新后重新选择');const title=$('title').value.trim(),description=$('description').value.trim(),tags=$('tags').value.split(/[,，]/).map(item=>item.trim()).filter(Boolean),mode=$('mode').value,shortTitle=$('short-title').value.trim(),sourceCredit=$('source-credit').value.trim(),category=$('category-id').value?Number($('category-id').value):null,copyright=Number($('copyright').value),rawSchedule=$('publish-at').value;if(!title)throw new Error('请填写标题');if(tags.length>10||new Set(tags).size!==tags.length||tags.some(tag=>!tag||textLength(tag)>20||/[#＃\n\r\t]/.test(tag)))throw new Error('每个平台最多 10 个不重复标签，每个最多 20 字，标签中不要填写 #');if(mode==='draft'&&selected.some(item=>item.platform!=='tencent'))throw new Error('只有视频号支持保存平台草稿；Bilibili 与抖音需选择投稿发布');if(mode==='draft'&&rawSchedule)throw new Error('保存平台草稿时不能设置定时发布');if(selected.some(item=>item.platform==='bilibili')&&(!category||!Number.isSafeInteger(category)))throw new Error('Bilibili 投稿必须填写分区 ID');if(selected.some(item=>item.platform==='bilibili')&&!tags.length)throw new Error('Bilibili 投稿至少需要一个标签');if(selected.some(item=>item.platform==='bilibili')&&copyright===2&&!sourceCredit)throw new Error('Bilibili 转载投稿必须填写来源');if(selected.some(item=>item.platform==='bilibili')&&copyright===1&&sourceCredit)throw new Error('Bilibili 原创投稿请清空转载来源');if(shortTitle&&(textLength(shortTitle)<7||textLength(shortTitle)>15))throw new Error('视频号短标题需为 7–15 字');const target_overrides=[];for(const account of selected){const limit={bilibili:80,douyin:30,tencent:100}[account.platform];if(textLength(title)>limit)throw new Error(({bilibili:'Bilibili',douyin:'抖音',tencent:'视频号'}[account.platform]||account.platform)+' 标题不能超过 '+limit+' 字');const schedule=scheduleFor(account.platform,rawSchedule),override={account_id:account.id,mode,...schedule},options={};if(account.platform==='douyin'&&$('ai-label').checked)options.declaration='内容由AI生成';if(account.platform==='tencent'){if(shortTitle)options.short_title=shortTitle;if($('ai-label').checked)options.content_label='含AI生成内容';}if(Object.keys(options).length)override.platform_options=options;target_overrides.push(override);}return {account_ids:ids,title,description,tags,category_id:selected.some(item=>item.platform==='bilibili')?category:null,mode,copyright:selected.some(item=>item.platform==='bilibili')?copyright:null,source_credit:selected.some(item=>item.platform==='bilibili')?sourceCredit:'',target_overrides};}
function render(items){const host=$('workflows');host.replaceChildren();if(!items.length){host.append(el('p','尚无流程。','muted'));return;}for(const item of items){const card=el('article',undefined,'item'),head=el('div',undefined,'row-spread'),copy=el('div');copy.append(el('h3',item.name),el('p',(stateNames[item.state]||item.state)+' · 修订 '+item.revision,'muted'));head.append(copy);const actions=el('div',undefined,'row');if(item.state==='awaiting_ai_review'&&item.code){if(item.code.endsWith('_review_required')&&!item.code.includes('restart')){const link=el('a','在编辑页核对时间轴','button-link');link.href='/edits';actions.append(link);}else{const button=el('button','确认开始当前 AI 步骤');button.type='button';button.addEventListener('click',()=>mutate(()=>api('/'+item.id+'/confirm-ai',{method:'POST',body:JSON.stringify({expected_revision:item.revision})})));actions.append(button);}}if(item.state==='awaiting_edit_confirmation'){const button=el('button','确认开始编辑');button.type='button';button.addEventListener('click',()=>mutate(()=>api('/'+item.id+'/confirm-edit',{method:'POST',body:JSON.stringify({expected_revision:item.revision})})));actions.append(button);}if(item.state==='awaiting_upload_confirmation'){const button=el('button','确认所选账号上传');button.type='button';button.addEventListener('click',()=>mutate(()=>api('/'+item.id+'/confirm-upload',{method:'POST',body:JSON.stringify({expected_revision:item.revision})})));actions.append(button);}const aiRetry=item.state==='attention_required'&&item.edit_project_id&&!item.edit_plan_id&&item.profile?.ai,renderRetry=item.state==='attention_required'&&item.edit_plan_id&&!item.edit_output_id&&!['edit_output_shape_invalid','edit_state_unknown'].includes(item.code);if(aiRetry||renderRetry){const retry=el('button',renderRetry?'创建编辑重试计划':'创建 AI 重试任务');retry.type='button';retry.addEventListener('click',()=>mutate(()=>api('/'+item.id+'/retry',{method:'POST',body:JSON.stringify({expected_revision:item.revision})})));actions.append(retry);}const advance=el('button','立即对账','secondary');advance.type='button';advance.addEventListener('click',()=>mutate(()=>api('/'+item.id+'/advance',{method:'POST'})));actions.append(advance);head.append(actions);card.append(head);if(aiRetry||renderRetry)card.append(el('p','上次运行中已经完成的远程 AI 批次或配音 cue 可能已计费；重试会重新发送完整步骤，确认后可能再次计费。','notice small'));if(item.code)card.append(el('p',codeNames[item.code]||item.code,'notice small'));card.append(el('p','Workflow '+item.id.slice(0,12)+' · 下载 '+String(item.batch_id||'等待').slice(0,12)+' · 编辑 '+String(item.edit_plan_id||'等待').slice(0,12),'mono small'));host.append(card);}}
async function refresh(){const items=await api('');render(items);}
async function mutate(work,{refreshAfter=true,successMessage='流程状态已更新。'}={}){if(busy)return;busy=true;document.querySelectorAll('button').forEach(node=>node.disabled=true);try{let result;try{result=await work();}catch(error){message(error.message,true);return;}if(refreshAfter)try{await refresh();}catch(error){message('操作已完成，但列表刷新失败；请点“刷新状态”：'+error.message,true);return result;}message(successMessage);return result;}finally{busy=false;document.querySelectorAll('button').forEach(node=>node.disabled=false);}}
$('workflow-form').addEventListener('submit',event=>{event.preventDefault();mutate(async()=>{if($('auto-upload').checked&&!$('auto-edit').checked)throw new Error('自动上传需要同时授权自动编辑');const editRecipe=recipe(),aiEnabled=Boolean(editRecipe.translation&&editRecipe.translation.enabled),transcription=aiEnabled?selectedEngine('transcription-engine'):null;if(aiEnabled&&!$('ai-egress').checked)throw new Error('请先核对并确认云端 AI 数据外发与费用范围');const intent={source_url:$('source-url').value.trim(),name:$('workflow-name').value.trim(),profile:{download_credential_mode:$('credential-mode').value,edit_recipe:editRecipe,ai:aiEnabled?{transcription_provider:transcription.provider,transcription_model:transcription.model}:null,upload:upload(),auto_confirm_edit:$('auto-edit').checked,auto_confirm_upload:$('auto-upload').checked,ai_data_egress_accepted:aiEnabled&&$('ai-egress').checked}};const pending=await pendingWorkflowKey(intent),payload={...intent,idempotency_key:pending.requestKey};await api('',{method:'POST',body:JSON.stringify(payload)});},{successMessage:'自动流程已创建；相同参数重试将复用该流程。'});});
$('refresh').addEventListener('click',()=>mutate(async()=>{},{successMessage:'流程状态已刷新。'}));
function invalidateAiEgress(){$('ai-egress').checked=false;renderAiEgress();}
$('speech-engine').addEventListener('change',()=>{renderVoiceOptions();invalidateAiEgress();});
for(const id of ['transcription-engine','translation-engine','translation-enabled','dubbing-enabled','segment-enabled','segment-start','segment-end'])$(id).addEventListener(id.includes('engine')||id.includes('enabled')?'change':'input',invalidateAiEgress);
async function loadAccounts(){const response=await fetch('/api/v1/uploads/accounts');if(response.ok){accounts=await response.json();renderAccounts();}}
async function loadAiCapabilities(){const response=await fetch('/api/v1/edits/ai/capabilities');if(response.ok){aiCapabilities=await response.json();if(!Array.isArray(aiCapabilities))aiCapabilities=[];}renderAiEngines();}
function schedule(){clearTimeout(pollTimer);pollTimer=setTimeout(async()=>{if(!document.hidden&&!busy)try{await refresh();}catch{}schedule();},2000);}
(async()=>{try{csrf=(await api('/session')).csrf_token;await Promise.all([loadAccounts(),loadAiCapabilities(),refresh()]);message('自动流程已连接。');}catch(error){message('连接失败：'+error.message,true);}finally{schedule();}})();
  </script>
</body></html>'''
