"""Upload workspace using the existing control page's visual language."""

UPLOAD_HTML = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Open Flame · 上传器</title>
<style>
:root{color-scheme:light;font-family:system-ui,sans-serif;background:#f5f6f8;color:#18202a}body{margin:0}main{max-width:880px;margin:0 auto;padding:40px 20px 80px}main>a{display:inline-flex;min-height:44px;align-items:center}h1{margin-bottom:8px}.muted{color:#5d6875}.card{background:white;border:1px solid #dfe3e8;border-radius:14px;padding:22px;margin-top:24px;box-shadow:0 8px 30px rgba(24,32,42,.06)}label{display:block;font-weight:650;margin:14px 0 7px}input,textarea,select,button{box-sizing:border-box;font:inherit}input,textarea,select{width:100%;border:1px solid #85858e;border-radius:8px;padding:10px 12px}input:not([type=checkbox]):not([type=radio]),select{min-height:44px}textarea{min-height:100px;resize:vertical}button{min-height:44px;margin-top:12px;border:0;border-radius:8px;background:#155eef;color:white;padding:10px 16px;font-weight:700;cursor:pointer}button:disabled{background:#e5e8ed;color:#5d6875;cursor:not-allowed}a{color:#155eef}summary{min-height:44px;box-sizing:border-box;padding:10px 0;cursor:pointer}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.row button{margin-top:0}.notice{border-left:4px solid #d97706;padding-left:12px}.danger{color:#a61b1b;font-weight:650}.item{min-width:0;border-top:1px solid #edf0f3;padding:14px 0}.item:first-child{border-top:0}.choice{display:flex;gap:9px;align-items:center;font-weight:400}.choice input{width:auto}.details{white-space:pre-wrap;overflow-wrap:anywhere;font-size:.92rem}code,#source-info,#engine-status{overflow-wrap:anywhere}#message{position:sticky;top:0;background:#f5f6f8;padding:12px 0;z-index:1}fieldset{border:1px solid #dfe3e8;border-radius:8px;margin-top:15px}legend{font-weight:650}.small{font-size:.9rem}.danger-action{border:1px solid #e0a8a3;background:#fff0ee;color:#a61b1b}.inline-confirm{margin-top:12px;padding:14px;border:1px solid #e0a8a3;border-radius:12px;background:#fff6f4}.inline-confirm p{margin-top:0}.storage-summary{margin:18px 0;padding:14px 16px;border-radius:12px;background:#f5f7fa}.storage-summary h3,.storage-summary p{margin:0}.storage-summary p+p{margin-top:8px}.numeric{font-variant-numeric:tabular-nums}[hidden]{display:none!important}
button{transition:transform 120ms cubic-bezier(.23,1,.32,1),background-color 120ms cubic-bezier(.23,1,.32,1),border-color 120ms cubic-bezier(.23,1,.32,1)}button:active:not(:disabled){transform:scale(.98)}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible,[tabindex="-1"]:focus-visible{outline:3px solid #0066cc;outline-offset:3px}.secondary{background:#eef2f8;color:#26354a}.login-panel{margin-top:20px;padding:22px;border:1px solid #b7ccf9;border-radius:12px;background:#f8faff;scroll-margin-top:80px}.login-content{display:flex;align-items:center;gap:24px;flex-wrap:wrap}.qr-frame{width:248px;height:248px;box-sizing:border-box;padding:12px;background:#fff;border:1px solid #e0e6f0;border-radius:10px;display:grid;place-items:center;flex:none}.qr-frame img{width:224px;height:224px;object-fit:contain;image-rendering:pixelated}.qr-placeholder{text-align:center;color:#66758c;padding:20px}.login-copy{flex:1;min-width:200px}.login-copy h3{margin:0 0 10px}.login-badge{display:inline-block;border-radius:20px;background:#e8effd;color:#174bb4;padding:4px 10px;font-size:.8rem;margin-bottom:12px}.login-actions{margin-top:18px}.login-actions button{margin-top:0}.login-panel[data-state=ready]{border-color:#75bda0;background:#f2fbf6}@media(max-width:520px){.login-content{justify-content:center}.login-copy{width:100%;min-width:0;text-align:center}.qr-frame{width:min(248px,100%);height:auto;aspect-ratio:1}.qr-frame img{width:100%;height:100%}.login-panel{padding:16px}.login-actions{justify-content:center}.inline-confirm .row{align-items:stretch;flex-direction:column}.inline-confirm .row button{width:100%}}@media(prefers-reduced-motion:reduce){button{transition:none}button:active:not(:disabled){transform:none}}@media(forced-colors:active){button,input,textarea,select,.inline-confirm{border:1px solid CanvasText}.danger-action{color:CanvasText;background:Canvas}}
#recover-scheduler,#more-jobs,#more-sources{min-height:44px;border-radius:12px;background:#f5f5f7;color:#1d1d1f;font-weight:600}#source-library{margin-top:18px}#source-library h4{margin:0}.source-meta{margin:6px 0;overflow-wrap:anywhere}.source-actions{margin-top:10px}.restore-panel{margin-top:18px;padding:18px;border:1px solid #b7ccf9;border-radius:12px;background:#f8faff}.restore-panel h3{margin-top:0}
</style></head><body><main>
<a href="/">← 返回下载器</a><h1>上传器</h1>
<p class="muted">将本地视频或下载成品发送到你选择的账号。支持 Bilibili、抖音和视频号；视频号还可选择保存平台草稿。</p>
<p class="notice">先创建本地草稿并核对内容，再逐个确认执行。上传账号单独登录；不会使用下载 Cookie。结果来自上游工具；审核和公开状态需在平台核对。</p>
<p id="message" role="status" aria-live="polite">正在连接上传器…</p>
<section class="card" aria-labelledby="engine-heading"><h2 id="engine-heading">上传引擎</h2>
<p id="engine-status" class="muted">正在读取状态…</p>
<p id="engine-integrity" class="muted small" hidden></p>
<p id="records-status" class="danger small" role="status" aria-live="polite" hidden></p>
<p id="engine-help" class="muted small">引擎就绪后，选择平台并点击“添加并扫码登录”，二维码会直接显示在本页。用对应手机 App 扫码并确认，登录状态会自动更新。</p>
<div class="row"><button id="refresh" type="button">刷新状态</button><button id="recover-scheduler" class="secondary" type="button" hidden>恢复上传调度</button></div></section>
<section class="card" aria-labelledby="accounts-heading"><h2 id="accounts-heading">1. 账号</h2>
<form id="account-form"><label for="account-platform">平台</label><select id="account-platform"><option value="bilibili">Bilibili</option><option value="douyin">抖音</option><option value="tencent">视频号</option></select>
<label for="account-name">账号备注（可选）</label><input id="account-name" maxlength="60" placeholder="例如：主账号；留空会自动命名">
<button type="submit">添加并扫码登录</button></form>
<div id="login-panel" class="login-panel" hidden tabindex="-1" role="region" aria-labelledby="login-title">
<div class="login-content"><div class="qr-frame"><img id="login-qr" alt="平台登录二维码，请用对应手机 App 扫码" hidden><p id="qr-placeholder" class="qr-placeholder">正在准备登录…</p></div>
<div class="login-copy"><span id="login-account" class="login-badge"></span><h3 id="login-title">扫码登录</h3><p id="login-description" class="muted" role="status" aria-live="polite"></p><p id="login-expiry" class="small muted"></p><p class="small muted">扫码仅用于登录；上传和发布需要另外确认。</p></div></div>
<div class="row login-actions"><button id="login-retry" type="button">重新获取二维码</button><button id="login-cancel" class="secondary" type="button">取消登录</button><button id="login-done" class="secondary" type="button" hidden>完成</button></div></div>
<div id="accounts"></div><div id="operations"></div></section>
<section class="card" aria-labelledby="source-heading"><h2 id="source-heading">2. 选择视频</h2>
<div id="asset-import" hidden><p>已从下载器选择一份成品。导入后会核验文件并创建独立上传副本。</p><button id="import-asset" type="button">导入此下载成品</button></div>
<form id="source-form"><label for="source-file">选择本地视频（最多 2 GiB）</label><input id="source-file" type="file" accept="video/*,.mp4,.mov,.mkv,.webm,.avi,.m4v" required><button type="submit">导入视频</button></form>
<div class="storage-summary" aria-labelledby="storage-heading"><h3 id="storage-heading">上传媒体占用</h3><p id="storage-summary" class="numeric muted">正在读取媒体占用…</p><p id="storage-warning" class="notice small" role="status" aria-live="polite" hidden></p></div>
<label for="source-id">可用于新草稿的视频</label><select id="source-id"><option value="">尚无可用视频</option></select><p id="source-info" class="muted small"></p><button id="more-sources" class="secondary" type="button" hidden>加载更多已导入视频</button>
<section aria-labelledby="source-library-heading"><h3 id="source-library-heading">受管媒体记录</h3><p class="muted small">Open-Flame 导入时创建独立受管副本。列表轮询快速检查路径、类型和大小；创建、确认、重试、删除及实际上传前会重新核对 SHA-256。删除受管副本不会删除你最初选择的本地文件或下载成品。</p><div id="source-library"></div></section>
<div id="source-restore-panel" class="restore-panel" hidden tabindex="-1" role="region" aria-labelledby="source-restore-heading" aria-describedby="source-restore-description"><h3 id="source-restore-heading">恢复受管副本</h3><p id="source-restore-description" class="muted"></p><form id="source-restore-form"><label for="source-restore-file">选择与历史记录完全相同的视频</label><input id="source-restore-file" type="file" accept="video/*,.mp4,.mov,.mkv,.webm,.avi,.m4v" required><p class="small muted">服务端只会在文件大小和 SHA-256 与历史记录完全一致时恢复同一媒体记录。</p><div class="row"><button type="submit">校验并恢复受管副本</button><button id="source-restore-cancel" class="secondary" type="button">取消</button></div></form></div></section>
<section class="card" aria-labelledby="compose-heading"><h2 id="compose-heading">3. 创建本地草稿</h2>
<form id="job-form"><fieldset><legend>选择接收账号</legend><div id="account-choices"><p class="muted">请先添加账号并登录或检查登录态。</p></div></fieldset>
<label for="title">标题</label><input id="title" required maxlength="100"><p id="title-help" class="muted small">请遵守所选平台标题长度限制，提交前会再次检查。</p>
<label for="description">简介</label><textarea id="description" maxlength="2000"></textarea>
<label for="tags">标签（逗号分隔，不加 #）</label><input id="tags" maxlength="500">
<fieldset id="tencent-options" hidden><legend>视频号操作</legend><label for="tencent-mode">确认后的动作</label><select id="tencent-mode"><option value="draft">上传并保存平台草稿</option><option value="publish">立即上传发布</option></select></fieldset>
<fieldset id="bilibili-options" hidden><legend>Bilibili 投稿信息</legend><label for="category-id">分区 ID（tid）</label><input id="category-id" type="number" min="1" step="1" placeholder="填写目标分区 ID">
<label for="copyright">投稿类型</label><select id="copyright"><option value="">请选择原创或转载</option><option value="1">原创</option><option value="2">转载</option></select>
<label for="source-credit">转载来源</label><input id="source-credit" maxlength="200" placeholder="转载时必须填写来源"></fieldset>
<p class="muted">Bilibili、抖音确认后立即投稿；视频号按上方所选动作执行。此按钮只创建本地草稿，不上传视频。</p><button type="submit">创建本地草稿并预览</button></form></section>
<section class="card" aria-labelledby="jobs-heading"><h2 id="jobs-heading">4. 核对草稿与任务</h2><p class="muted small">若结果不确定，请先在平台查看是否已经收到视频，再决定是否创建新的草稿。取消不能撤回平台已经接收的内容。</p><div id="jobs"></div><button id="more-jobs" class="secondary" type="button" hidden>加载更早任务</button></section>
</main><script>
'use strict';
const $=id=>document.getElementById(id);
const platformNames={bilibili:'Bilibili',douyin:'抖音',tencent:'视频号'};
const mediaStateNames={present:'副本可用',missing:'副本缺失',deleted:'副本已删除',changed:'内容或记录状态已变化',unsafe:'路径不安全'};
const stateNames={draft:'本地草稿',queued:'等待执行',running:'执行中',submitted:'上游报告投稿完成',draft_saved:'上游报告草稿已保存',failed:'失败',canceled:'已取消',unknown:'结果不确定',succeeded:'完成',ready:'可用',invalid:'登录失效',unchecked:'尚未检查',checking:'检查中',disconnected:'已断开本地账号'};
const codeNames={backend_unavailable:'上传引擎未安装或不可用',runtime_unavailable:'上传引擎未安装或不可用',runtime_missing:'上传引擎未安装',runtime_upgrade_required:'旧运行环境需要重建（保留账号与上传数据），见运行环境说明',account_not_ready:'请先登录或检查账号',authentication_required:'需要重新登录',login_required:'需要重新登录',source_changed:'视频校验不一致，请重新导入',source_too_large:'视频超过 2 GiB',source_empty:'视频为空',invalid_metadata:'投稿信息不符合平台要求',unknown_acknowledgement_required:'请先核对平台结果',upload_request_forbidden:'页面会话失效或请求来源不匹配，请刷新页面',uploader_stopped:'上传器已停止，请重启应用',internal_error:'上传器内部错误'};
Object.assign(codeNames,{ready:'就绪',account_ready:'登录态可用',account_name_exists:'该平台已有同名账号，请修改备注',account_not_found:'账号不存在',account_operation_active:'该账号已有登录或检查任务，请等待或取消',account_missing:'尚无登录态，请先登录',account_invalid:'登录态已失效，请重新登录',login_failed:'登录未完成，请重试',login_terminal_unavailable:'当前环境无法打开 Bilibili 登录终端',backend_failed:'上传引擎执行失败，请检查运行环境',runtime_invalid:'运行环境校验失败，请按文档重新准备',invalid_accounts:'请重新选择接收账号',invalid_identifier:'所选记录无效，请刷新页面',bilibili_category_required:'请填写 Bilibili 分区 ID',bilibili_copyright_required:'请选择 Bilibili 原创或转载',account_session_changed:'账号已重新登录，请核对后再次确认',runtime_busy:'运行环境正在安装，请稍后刷新',bilibili_tags_required:'Bilibili 投稿至少需要一个标签',source_credit_required:'转载必须填写来源',source_not_found:'视频不存在，请重新导入',source_hash_mismatch:'下载成品校验不一致，请检查原件',source_size_invalid:'视频为空或超过 2 GiB',source_unavailable:'视频不可用，请重新导入',unsupported_video_type:'不支持此视频格式',source_changed:'视频已发生变化，请重新导入',title_too_long:'标题超过所选平台的长度限制',invalid_tags:'最多 10 个不重复标签，每个最多 20 字',invalid_source_name:'文件名称无效',upload_storage_full:'上传目录可用空间不足',unsafe_upload_file:'文件或目录不符合本地存储要求',verify_remote_result_first:'请先在平台核对结果，再勾选确认重试',interrupted_result_unknown:'上次上传中断，请先在平台核对是否已收到',upstream_result_unknown:'上游结果不确定，请在平台核对',upstream_submitted:'上游工具报告投稿完成，请在平台核对审核状态',upstream_draft_saved:'上游工具报告草稿已保存',restart_confirmation_required:'应用重启后需要再次确认',operation_interrupted:'上次账号操作中断，请重新检查',job_requires_new_draft:'此任务不能再次提交，请创建新草稿',job_not_found:'任务不存在',retry_not_allowed:'该任务当前不能重试',draft_mode_unsupported:'所选平台不支持草稿模式',idempotency_conflict:'提交内容已变化，请刷新页面后重新创建草稿',upload_worker_stopping:'上传器正在停止，请稍后重启',canceled:'已取消',cancelled:'已取消'});
let csrf='', snapshot={accounts:[],sources:[],jobs:[],operations:[],status:{},storage:null}, busy=false, pollPromise=null, timer=null, pageActive=true;
let draftSubmission=null, sourcesInitialized=false, jobToFocus=null;const unknownAcknowledgements=new Set(), jobDetailsOpen=new Map();
let sourceNextCursor=null,jobNextCursor=null,sourceHistoryExpanded=false,jobHistoryExpanded=false;
const pinnedJobs=new Map(),pinnedSources=new Map();
let loginOperationId=null, loginAccountId=null, qrObjectUrl=null, qrKey=null, qrGeneration=0, qrRequest=null, loginTimer=null, restoreSourceId=null;
const accountDisconnectOpen=new Set(),sourceDeleteOpen=new Set();let requestedFocusKey=null;
const loginPhases={queued:['等待登录通道','前面的账号操作完成后，会自动显示二维码。'],preparing:['正在获取二维码','正在连接平台，请稍候。'],waiting_scan:['请扫码登录','用对应手机 App 扫描左侧二维码，并在手机上确认。'],scanned:['已扫码，等待手机确认','请在手机上确认本次登录，页面会自动更新。'],verification_required:['平台要求额外验证','请完成平台要求的验证。如仍无法继续，可取消后重新扫码。'],expired:['二维码已过期','点击“重新获取二维码”开始新的登录。'],ready:['登录成功','账号已连接，可以继续创建上传草稿。'],failed:['登录未完成','可以重新获取二维码再试一次。'],canceled:['登录已取消','需要时可以重新扫码登录。']};
Object.assign(codeNames,{login_owned_by_other_instance:'请在正在运行上传任务的应用中扫码登录',login_expired:'二维码已过期',login_qr_expired:'二维码已过期',login_timeout:'登录等待超时，请重新扫码',login_qr_unavailable:'暂时无法获取二维码，请重试',login_verification_required:'平台要求额外验证，请完成验证后重试'});
Object.assign(codeNames,{upload_database_unavailable:'上传数据库暂时不可用',scheduler_database_unavailable:'上传数据库暂时不可用',scheduler_failed:'上传调度发生内部故障',scheduler_recovery_failed:'上传调度仍无法恢复，请检查本地存储',scheduler_recovered:'上传调度已恢复；中断任务需要重新核对或确认',scheduler_owned_by_other_instance:'由另一个应用实例执行'});
Object.assign(codeNames,{account_busy:'账号仍有正在执行的操作或任务，请等待结束或先取消',account_upload_active:'该账号仍有上传正在执行，请等待结束',account_disconnected:'本地账号已断开',account_disconnect_cleanup_failed:'账号断开后的本地清理未完成，请重试',account_disconnected_confirmation_revoked:'账号断开后，旧确认已撤回，请重新登录并核对'});
Object.assign(codeNames,{source_media_in_use:'仍有未完成任务引用此视频',source_in_use:'仍有未完成任务引用此视频',source_media_missing:'受管副本缺失，请重新导入完全相同的视频',source_reimport_required:'受管副本不可用，请重新导入完全相同的视频',source_media_hash_mismatch:'所选视频与历史记录不一致',source_restore_mismatch:'所选视频与历史记录不一致，受管副本没有恢复',source_restore_conflict:'媒体状态已经变化，请刷新后再恢复',source_restore_failed:'恢复受管副本失败，原记录保持不变',source_already_present:'受管副本已经可用',source_delete_failed:'删除受管副本失败，原文件保持不变',source_delete_cleanup_failed:'删除记录已保存，但隔离副本清理失败；请检查容量与未登记文件清单',source_delete_rollback_failed:'删除更新失败且原路径未能恢复；请立即检查上传媒体目录',source_storage_invalid:'上传媒体目录状态不安全，请检查本地存储',binary_source_required:'恢复受管副本需要选择本地视频文件'});
function clearQR(){qrGeneration++;if(qrRequest)qrRequest.abort();qrRequest=null;if(qrObjectUrl)URL.revokeObjectURL(qrObjectUrl);qrObjectUrl=null;qrKey=null;$('login-qr').hidden=true;$('login-qr').removeAttribute('src');}
function selectedLogin(){return snapshot.operations.find(item=>item.id===loginOperationId&&item.action==='login');}
function qrStillCurrent(id,revision){const op=selectedLogin();return pageActive&&op&&op.id===id&&op.qr_revision===revision&&op.state==='running'&&op.qr_available&&op.login_phase==='waiting_scan'&&(!op.expires_at||op.expires_at*1000>Date.now());}
async function loadLoginQR(op){
  const key=op.id+':'+op.qr_revision;if(qrKey===key)return;clearQR();qrKey=key;
  const generation=qrGeneration;const controller=new AbortController();qrRequest=controller;
  const timeout=setTimeout(()=>controller.abort(),15000);
  try{
    const response=await fetch('/api/v1/uploads/operations/'+encodeURIComponent(op.id)+'/qr',{headers:new Headers({'X-Upload-CSRF':csrf}),cache:'no-store',signal:controller.signal});
    if(!response.ok||response.headers.get('Content-Type')?.split(';')[0]!=='image/png')throw new Error('qr_unavailable');
    const blob=await response.blob();if(blob.size>524288)throw new Error('qr_invalid');
    if(generation!==qrGeneration||!qrStillCurrent(op.id,op.qr_revision))return;
    qrObjectUrl=URL.createObjectURL(blob);$('login-qr').src=qrObjectUrl;$('login-qr').hidden=false;$('qr-placeholder').hidden=true;
  }catch(error){if(generation===qrGeneration){qrKey=null;$('qr-placeholder').hidden=false;$('qr-placeholder').textContent='二维码暂未就绪，正在重试…';}}
  finally{clearTimeout(timeout);if(qrRequest===controller)qrRequest=null;}
}
function renderLogin(){
  if(!pageActive){clearQR();return;}
  if(!loginOperationId){const active=snapshot.operations.find(item=>item.action==='login'&&['queued','running'].includes(item.state));if(active){loginOperationId=active.id;loginAccountId=active.account_id;}}
  const op=selectedLogin();if(!op){$('login-panel').hidden=true;clearQR();return;}
  const account=snapshot.accounts.find(item=>item.id===op.account_id);loginAccountId=op.account_id;
  let phase=op.state==='running'?(op.login_phase||'preparing'):op.state;
  if(op.code==='cancellation_requested')phase='canceling';
  if(op.state==='failed'&&['login_qr_expired','login_expired','login_timeout'].includes(op.code))phase='expired';
  if(op.state==='failed'&&op.code==='login_verification_required')phase='verification_required';
  if(op.expires_at&&op.expires_at*1000<=Date.now()&&phase==='waiting_scan')phase='expired';
  const copy=phase==='canceling'?['正在取消登录','正在关闭本次登录会话。']:loginPhases[phase]||loginPhases.preparing;
  $('login-panel').hidden=false;$('login-panel').dataset.state=phase;
  $('login-account').textContent=account?platformNames[account.platform]+' · '+account.name:'账号登录';
  $('login-title').textContent=copy[0];$('login-description').textContent=copy[1]+(op.state==='failed'&&op.code?' '+codeText(op.code):'');
  if(phase==='waiting_scan'&&account){const app={bilibili:'Bilibili App',douyin:'抖音 App',tencent:'微信'}[account.platform];$('login-description').textContent='使用'+app+'扫码，并在手机上确认本次登录。'+(account.platform==='bilibili'?'平台授权页可能显示 TV 客户端。':'');}
  $('login-expiry').textContent=phase==='waiting_scan'&&op.expires_at?'约 '+Math.max(0,Math.ceil(op.expires_at-Date.now()/1000))+' 秒后过期':'';
  const active=['queued','running'].includes(op.state);
  $('login-cancel').hidden=!active;$('login-retry').hidden=phase==='ready';$('login-done').hidden=active;
  $('login-retry').disabled=busy||phase==='canceling';$('login-cancel').disabled=busy||phase==='canceling';
  if(phase==='waiting_scan'&&op.qr_available){$('qr-placeholder').textContent='正在加载二维码…';loadLoginQR(op);}
  else{clearQR();$('qr-placeholder').hidden=false;$('qr-placeholder').textContent=phase==='ready'?'✓ 登录成功':copy[0];}
}
async function startLogin(accountId){clearQR();loginAccountId=accountId;message('正在创建登录会话…');const op=await api('/accounts/'+encodeURIComponent(accountId)+'/login',{method:'POST'});loginOperationId=op.id;message('本页会自动更新登录状态。');await refresh();$('login-panel').focus();}
async function restartLogin(){const op=selectedLogin();const accountId=loginAccountId;if(!accountId)return;clearQR();
  if(op&&['queued','running'].includes(op.state)){await api('/operations/'+encodeURIComponent(op.id)+'/cancel',{method:'POST'});
    for(let attempt=0;attempt<50;attempt++){const operations=await api('/operations');const previous=operations.find(item=>item.id===op.id);if(!previous||!['queued','running'].includes(previous.state))break;if(attempt===49)throw new Error('正在结束上一次登录，请稍后重新获取二维码。');await new Promise(resolve=>setTimeout(resolve,150));}}
  await startLogin(accountId);
}
$('login-retry').addEventListener('click',()=>mutate(restartLogin));
$('login-cancel').addEventListener('click',()=>mutate(async()=>{const op=selectedLogin();clearQR();if(op)await api('/operations/'+encodeURIComponent(op.id)+'/cancel',{method:'POST'});message('已取消本次登录。');}));
$('login-done').addEventListener('click',()=>{clearQR();loginOperationId=null;loginAccountId=null;$('login-panel').hidden=true;});
function scheduleLoginTick(){if(loginTimer!==null)clearTimeout(loginTimer);loginTimer=pageActive?setTimeout(tickLogin,1000):null;}
function tickLogin(){if(loginTimer!==null)clearTimeout(loginTimer);loginTimer=null;if(!pageActive)return;if(selectedLogin()&&!document.hidden)renderLogin();scheduleLoginTick();}
scheduleLoginTick();
function element(tag,text,className){const item=document.createElement(tag);if(text!==undefined)item.textContent=text;if(className)item.className=className;return item;}
function codeText(code){return code?codeNames[code]||code:'';}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'danger':'muted';}
async function api(path,options={}){
  const headers=new Headers(options.headers||{});
  if(options.method && options.method!=='GET')headers.set('X-Upload-CSRF',csrf);
  if(options.json!==undefined){headers.set('Content-Type','application/json');options.body=JSON.stringify(options.json);delete options.json;}
  const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),options.body instanceof Blob?600000:30000);
  try{const response=await fetch('/api/v1/uploads'+path,{...options,headers,cache:'no-store',signal:controller.signal});
    let payload;try{payload=await response.json();}catch{throw new Error('服务器返回了无法读取的响应');}
    if(!response.ok){const detail=typeof payload.detail==='string'?codeText(payload.detail):'请检查必填信息和平台限制';throw new Error(detail+'（HTTP '+response.status+'）');}return payload;
  }finally{clearTimeout(timeout);}
}
function button(text,action){const item=element('button',text);item.type='button';item.disabled=busy;item.addEventListener('click',()=>mutate(action));return item;}
function localButton(text,action){const item=element('button',text);item.type='button';item.disabled=busy;item.addEventListener('click',()=>{if(!busy)action();});return item;}
function focusContext(){return {key:document.activeElement?.dataset?.focusKey||null,targets:new Map()};}
function focusControl(context,item,key){item.dataset.focusKey=key;context.targets.set(key,item);return item;}
function restoreRenderedFocus(context){const key=requestedFocusKey||context.key,target=context.targets.get(key);if(target&&!target.disabled){target.focus({preventScroll:true});if(requestedFocusKey===key)requestedFocusKey=null;}}
function disconnectedTime(value){if(!value)return '';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString('zh-CN');}
function formatBytes(value){const bytes=Math.max(0,Number(value)||0);if(bytes<1024)return Math.round(bytes)+' B';if(bytes<1048576)return (bytes/1024).toFixed(1)+' KiB';if(bytes<1073741824)return (bytes/1048576).toFixed(1)+' MiB';return (bytes/1073741824).toFixed(1)+' GiB';}
async function disconnectLocalAccount(account,retry=false){try{const result=await api('/accounts/'+encodeURIComponent(account.id)+'/disconnect',{method:'POST'});accountDisconnectOpen.delete(account.id);snapshot.accounts=snapshot.accounts.map(entry=>entry.id===account.id?result.account:entry);if(loginAccountId===account.id){clearQR();loginOperationId=null;loginAccountId=null;$('login-panel').hidden=true;}message(retry?'本地登录清理已完成。':'已断开本地账号；已撤回 '+result.revoked_confirmation_count+' 项旧确认，取消 '+result.canceled_operation_count+' 项待执行账号操作。');}catch(error){await refresh();throw error;}}
function renderStorage(){const storage=snapshot.storage;if(!storage){$('storage-summary').textContent='媒体占用暂不可用。';$('storage-warning').textContent='';$('storage-warning').hidden=true;return;}
  const count=value=>Math.max(0,Number(value)||0),parts=['受管副本 '+formatBytes(storage.managed_bytes),count(storage.registered_source_count)+' 份记录',count(storage.present_source_count)+' 份可用',count(storage.missing_source_count)+' 份缺失',count(storage.deleted_source_count)+' 份已删除'];if(count(storage.changed_source_count))parts.push(count(storage.changed_source_count)+' 份内容变化');if(count(storage.unsafe_source_count))parts.push(count(storage.unsafe_source_count)+' 份路径不安全');if(count(storage.orphan_file_count))parts.push(count(storage.orphan_file_count)+' 份未登记文件（'+formatBytes(storage.orphan_bytes)+'）');$('storage-summary').textContent=parts.join(' · ');
  const warnings=[];if(storage.low_space)warnings.push('本地可用空间仅 '+formatBytes(storage.free_bytes)+'；导入视频后还需保留 '+formatBytes(storage.reserve_bytes)+'。请先释放空间。');if(count(storage.changed_source_count)||count(storage.unsafe_source_count)||count(storage.orphan_file_count)||count(storage.unsafe_entry_count))warnings.push('存储审计发现异常或未登记条目；这里只读显示，不会自动清理，请检查上传媒体目录。');const warning=warnings.join(' ');if($('storage-warning').textContent!==warning)$('storage-warning').textContent=warning;$('storage-warning').hidden=!warning;}
async function mutate(action){if(busy)return;busy=true;document.querySelectorAll('button').forEach(item=>item.disabled=true);
  try{if(pollPromise)await pollPromise;await action();await refresh();}catch(error){message(error.message||String(error),true);}
  finally{busy=false;document.querySelectorAll('button').forEach(item=>item.disabled=false);renderAccounts();renderSources();renderJobs();renderLogin();if(jobToFocus){let target=[...$('jobs').children].find(item=>item.dataset.jobId===jobToFocus);if(!target){try{const record=await api('/jobs/'+encodeURIComponent(jobToFocus));pinJob(record);snapshot.jobs=applyUpdates(snapshot.jobs,[record]);if(!snapshot.sources.some(item=>item.id===record.source_id)){const source=await api('/sources/'+encodeURIComponent(record.source_id));pinSource(source);snapshot.sources=applyUpdates(snapshot.sources,[source]);renderSources();}renderJobs();target=[...$('jobs').children].find(item=>item.dataset.jobId===jobToFocus);}catch{}}jobToFocus=null;if(target){target.scrollIntoView({block:'nearest'});target.focus();}}}}
function selectedAccounts(){return [...document.querySelectorAll('#account-choices input:checked')].map(item=>item.value);}
function updateMetadata(){const selected=new Set(selectedAccounts());const platforms=snapshot.accounts.filter(item=>selected.has(item.id)).map(item=>item.platform);const bili=platforms.includes('bilibili');$('bilibili-options').hidden=!bili;$('tencent-options').hidden=!platforms.includes('tencent');$('category-id').required=bili;$('copyright').required=bili;$('source-credit').required=bili&&$('copyright').value==='2';
  const limits=(snapshot.status.platforms||[]).filter(item=>platforms.includes(item.id)).map(item=>platformNames[item.id]+' '+item.title_limit+' 字');$('title-help').textContent=limits.length?'标题限制：'+limits.join('；'):'请先选择接收账号。';}
function renderAccounts(){const selected=new Set(selectedAccounts()),focus=focusContext();$('accounts').replaceChildren();$('account-choices').replaceChildren();
  for(const account of snapshot.accounts){const connected=(account.lifecycle_state||'active')==='active',item=element('div',undefined,'item');item.dataset.accountId=account.id;item.append(element('strong',platformNames[account.platform]+' · '+account.name));
    const visibleState=connected?(stateNames[account.auth_state]||account.auth_state):stateNames.disconnected;item.append(element('p',visibleState+(account.code?' · '+codeText(account.code):''),'muted'));
    if(!connected){const when=disconnectedTime(account.disconnected_at),cleanupFailed=account.code==='account_disconnect_cleanup_failed';item.append(element('p',(cleanupFailed?'此历史账号已停用，但本地登录文件清理尚未完成。账号不能再用于登录或上传，请重试清理。':'此历史账号仅保留任务归属与备注；本地登录已移除，不会撤销平台侧授权，平台会话需要在平台内另行处理。')+(when?' 断开时间：'+when:''),'small muted'));if(cleanupFailed){const retryCleanup=focusControl(focus,button('重试清理本地登录',()=>disconnectLocalAccount(account,true)),'account:'+account.id+':cleanup');retryCleanup.className='secondary';item.append(retryCleanup);}accountDisconnectOpen.delete(account.id);$('accounts').append(item);continue;}
    const actions=element('div',undefined,'row'),active=snapshot.operations.find(op=>op.account_id===account.id&&['queued','running'].includes(op.state));
    if(active&&active.action==='login')actions.append(focusControl(focus,button('查看二维码',async()=>{loginOperationId=active.id;loginAccountId=account.id;renderLogin();$('login-panel').focus();}),'account:'+account.id+':qr'));
    else{const login=focusControl(focus,button(account.auth_state==='ready'?'重新扫码登录':'扫码登录',()=>startLogin(account.id)),'account:'+account.id+':login');login.disabled=busy||!!active;actions.append(login);}
    const checkLogin=focusControl(focus,button('检查登录态',async()=>{await api('/accounts/'+encodeURIComponent(account.id)+'/check',{method:'POST'});message('登录态检查已排队。');}),'account:'+account.id+':check');checkLogin.className='secondary';checkLogin.disabled=busy||!!active;actions.append(checkLogin);
    const disconnect=focusControl(focus,localButton('断开本地账号',()=>{accountDisconnectOpen.add(account.id);requestedFocusKey='account:'+account.id+':disconnect-confirm';renderAccounts();}),'account:'+account.id+':disconnect');disconnect.className='danger-action';disconnect.disabled=busy||!!active;actions.append(disconnect);item.append(actions);
    if(active)item.append(element('p','账号操作进行中；结束或取消后才能断开本地账号。','small muted'));
    if(accountDisconnectOpen.has(account.id)){const confirm=element('div',undefined,'inline-confirm');confirm.setAttribute('role','group');confirm.setAttribute('aria-label','确认断开本地账号');confirm.append(element('p','只会移除 Open-Flame 的本地登录状态，不会撤销平台侧授权。尚未执行的旧确认会退回本地草稿；历史任务和媒体记录继续保留。'));
      const confirmActions=element('div',undefined,'row'),apply=focusControl(focus,button('确认断开本地账号',()=>disconnectLocalAccount(account)),'account:'+account.id+':disconnect-confirm');apply.className='danger-action';apply.disabled=busy||!!active;
      const dismiss=focusControl(focus,localButton('取消',()=>{accountDisconnectOpen.delete(account.id);requestedFocusKey='account:'+account.id+':disconnect';renderAccounts();}),'account:'+account.id+':disconnect-cancel');dismiss.className='secondary';confirmActions.append(apply,dismiss);confirm.append(confirmActions);item.append(confirm);}
    $('accounts').append(item);
    const choice=element('label',undefined,'choice'),check=focusControl(focus,element('input'),'account:'+account.id+':choice');check.type='checkbox';check.value=account.id;check.checked=selected.has(account.id);check.addEventListener('change',updateMetadata);choice.append(check,element('span',platformNames[account.platform]+' · '+account.name+'（'+(stateNames[account.auth_state]||account.auth_state)+'）'));$('account-choices').append(choice);}
  if(!$('account-choices').children.length)$('account-choices').append(element('p',snapshot.accounts.length?'请添加或连接可用账号。':'请先添加账号。','muted'));updateMetadata();
  $('operations').replaceChildren();for(const operation of snapshot.operations.filter(item=>item.action!=='login'&&['queued','running','failed','unknown'].includes(item.state)).slice(0,5)){const account=snapshot.accounts.find(item=>item.id===operation.account_id);const item=element('div',undefined,'item');item.append(element('p',(account?account.name:'账号操作')+' · '+(operation.action==='login'?'登录':'检查')+' · '+(stateNames[operation.state]||operation.state)+' '+codeText(operation.code)));if(['queued','running'].includes(operation.state))item.append(focusControl(focus,button('取消账号操作',async()=>{await api('/operations/'+encodeURIComponent(operation.id)+'/cancel',{method:'POST'});message('已请求取消账号操作。');}),'operation:'+operation.id+':cancel'));$('operations').append(item);}restoreRenderedFocus(focus);
}
function mergeFirstPage(first,existing,keepExisting){if(!keepExisting)return [...first];const seen=new Set(first.map(item=>item.id));return [...first,...existing.filter(item=>!seen.has(item.id))];}
function appendPage(existing,items){const seen=new Set(existing.map(item=>item.id));return [...existing,...items.filter(item=>!seen.has(item.id))];}
function remember(map,item){if(!item||!item.id)return;map.delete(item.id);map.set(item.id,item);while(map.size>64)map.delete(map.keys().next().value);}
function pinJob(item){remember(pinnedJobs,item);}function pinSource(item){remember(pinnedSources,item);}
function applyUpdates(existing,updates){const fresh=new Map(updates.map(item=>[item.id,item])),seen=new Set();const result=existing.map(item=>{seen.add(item.id);return fresh.get(item.id)||item;});for(const item of updates)if(!seen.has(item.id))result.push(item);return result;}
function sourceMediaState(source){return source.media_state||(source.media_present===false?'missing':'present');}
function sourceMediaPresent(source){return sourceMediaState(source)==='present'&&source.media_present!==false;}
function renderSources(){const previous=$('source-id').value,focus=focusContext(),usable=snapshot.sources.filter(sourceMediaPresent);$('source-id').replaceChildren(element('option','请选择视频'));$('source-id').firstChild.value='';for(const source of usable){const option=element('option',source.name+' · '+(source.size/1048576).toFixed(1)+' MiB');option.value=source.id;$('source-id').append(option);}if(usable.some(item=>item.id===previous))$('source-id').value=previous;else $('source-id').value=!sourcesInitialized&&usable.length?usable[0].id:'';sourcesInitialized=true;$('more-sources').hidden=!sourceNextCursor;showSource();$('source-library').replaceChildren();
  if(!snapshot.sources.length)$('source-library').append(element('p','尚无受管媒体记录。','muted'));
  for(const source of snapshot.sources){const state=sourceMediaState(source),references=Math.max(0,Number(source.active_reference_count)||0),item=focusControl(focus,element('article',undefined,'item'),'source:'+source.id+':card');item.dataset.sourceId=source.id;item.tabIndex=-1;item.append(element('h4',source.name));item.append(element('p',mediaStateNames[state]||state+' · '+formatBytes(source.size),'source-meta muted'));item.append(element('p','大小：'+formatBytes(source.size)+' · SHA-256：'+source.sha256,'source-meta small muted'));
    if(source.media_deleted_at)item.append(element('p','删除时间：'+disconnectedTime(source.media_deleted_at),'source-meta small muted'));
    if(sourceMediaPresent(source)){const actions=element('div',undefined,'row source-actions'),remove=focusControl(focus,localButton('删除受管副本',()=>{pinSource(source);sourceDeleteOpen.add(source.id);requestedFocusKey='source:'+source.id+':delete-confirm';renderSources();}),'source:'+source.id+':delete');remove.className='danger-action';remove.disabled=busy||source.can_delete===false||references>0;actions.append(remove);item.append(actions);if(references>0)item.append(element('p',references+' 个未完成任务正在引用此副本；任务结束或取消后才能删除。','small muted'));else if(source.can_delete===false)item.append(element('p','当前不能删除此受管副本，请刷新后再试。','small muted'));
      if(sourceDeleteOpen.has(source.id)&&!remove.disabled){const confirm=element('div',undefined,'inline-confirm');confirm.setAttribute('role','group');confirm.setAttribute('aria-label','确认删除受管副本');confirm.append(element('p','只删除 Open-Flame 的受管副本；你最初选择的原始文件和下载成品保持不变。媒体记录和历史任务继续保留。'));
        const buttons=element('div',undefined,'row'),apply=focusControl(focus,button('确认删除受管副本',async()=>{const updated=await api('/sources/'+encodeURIComponent(source.id)+'/media',{method:'DELETE'});pinSource(updated);snapshot.sources=applyUpdates(snapshot.sources,[updated]);sourceDeleteOpen.delete(source.id);if($('source-id').value===source.id)$('source-id').value='';requestedFocusKey='source:'+source.id+':card';message('受管副本已删除；原始文件和下载成品保持不变。');}),'source:'+source.id+':delete-confirm'),dismiss=focusControl(focus,localButton('取消',()=>{sourceDeleteOpen.delete(source.id);requestedFocusKey='source:'+source.id+':delete';renderSources();}),'source:'+source.id+':delete-cancel');apply.className='danger-action';dismiss.className='secondary';buttons.append(apply,dismiss);confirm.append(buttons);item.append(confirm);}}
    else{sourceDeleteOpen.delete(source.id);if(['missing','deleted'].includes(state)){item.append(element('p','此记录不能用于新草稿。选择与历史大小和 SHA-256 完全一致的视频，可恢复受管副本并继续处理旧任务。','small notice'));const restore=focusControl(focus,localButton('重新导入相同视频',()=>openSourceRestore(source.id)),'source:'+source.id+':restore');restore.className='secondary';item.append(restore);}else if(state==='changed')item.append(element('p','受管路径中的内容已变化，已停止使用。请先移走变化文件并刷新，待记录显示缺失后再恢复受管副本。','small notice'));else item.append(element('p','受管媒体路径状态不安全，已停止使用。请检查上传媒体目录后刷新。','small notice'));}
    $('source-library').append(item);}
  if(restoreSourceId){const restoring=snapshot.sources.find(item=>item.id===restoreSourceId);if(!restoring||sourceMediaPresent(restoring)){restoreSourceId=null;$('source-restore-panel').hidden=true;$('source-restore-file').value='';}else{$('source-restore-heading').textContent='恢复受管副本 · '+restoring.name;$('source-restore-description').textContent='将文件校验后恢复到现有媒体记录；需要完全匹配 '+formatBytes(restoring.size)+' 与 SHA-256 '+restoring.sha256+'。';}}
  restoreRenderedFocus(focus);
}
function showSource(){const source=snapshot.sources.find(item=>item.id===$('source-id').value);$('source-info').textContent=source?'SHA-256：'+source.sha256:'';}
function openSourceRestore(sourceId){const source=snapshot.sources.find(item=>item.id===sourceId);if(!source||!['missing','deleted'].includes(sourceMediaState(source)))return;pinSource(source);restoreSourceId=sourceId;$('source-restore-heading').textContent='恢复受管副本 · '+source.name;$('source-restore-description').textContent='将文件校验后恢复到现有媒体记录；需要完全匹配 '+formatBytes(source.size)+' 与 SHA-256 '+source.sha256+'。';$('source-restore-panel').hidden=false;$('source-restore-file').focus({preventScroll:true});}
function closeSourceRestore(){const sourceId=restoreSourceId;restoreSourceId=null;$('source-restore-panel').hidden=true;$('source-restore-file').value='';if(sourceId){requestedFocusKey='source:'+sourceId+':restore';renderSources();}}
function jobMediaState(job,source){if(job.source_media_state)return job.source_media_state;if(job.source_media_present===false)return 'missing';return source?sourceMediaState(source):'present';}
function jobAccountActive(job){if(job.account_lifecycle_state)return job.account_lifecycle_state==='active';const account=job.account_id?snapshot.accounts.find(item=>item.id===job.account_id):null;return !account||(account.lifecycle_state||'active')==='active';}
function renderJobs(){for(const preview of $('jobs').querySelectorAll('details[data-job-id]'))jobDetailsOpen.set(preview.dataset.jobId,preview.open);const focus=focusContext();$('jobs').replaceChildren();$('more-jobs').hidden=!jobNextCursor;if(!snapshot.jobs.length){$('jobs').append(element('p','尚无上传任务。','muted'));restoreRenderedFocus(focus);return;}
  for(const job of snapshot.jobs){const item=focusControl(focus,element('article',undefined,'item'),'job:'+job.id+':card');item.dataset.jobId=job.id;item.tabIndex=-1;const source=snapshot.sources.find(entry=>entry.id===job.source_id),mediaState=jobMediaState(job,source),mediaReady=mediaState==='present'&&job.source_media_present!==false,accountReady=jobAccountActive(job),actionReady=mediaReady&&accountReady;item.append(element('strong',platformNames[job.platform]+' · '+job.account_name+' · '+(stateNames[job.state]||job.state)));item.append(element('p',job.title));
    const preview=element('details');preview.dataset.jobId=job.id;preview.open=jobDetailsOpen.has(job.id)?jobDetailsOpen.get(job.id):job.state==='draft';preview.append(focusControl(focus,element('summary','查看投稿信息'),'job:'+job.id+':summary'));preview.append(element('p','视频：'+(source?source.name:(job.source_name||'已登记视频'))+'\n媒体状态：'+(mediaStateNames[mediaState]||mediaState)+'\n简介：'+(job.description||'（空）')+'\n标签：'+(job.tags||[]).join('，')+'\n动作：'+(job.mode==='draft'?'保存平台草稿':'立即投稿')+(job.platform==='bilibili'?'\n分区 ID：'+job.category_id+'\n类型：'+(job.copyright===1?'原创':'转载')+(job.copyright===2?'\n来源：'+job.source_credit:''):''),'details'));item.append(preview);if(job.code)item.append(element('p',codeText(job.code),job.state==='failed'||job.state==='unknown'?'danger':'muted'));
    if(!mediaReady)item.append(element('p','此任务的受管副本'+(mediaStateNames[mediaState]||'不可用')+'；请先恢复受管副本：在上方媒体记录中重新导入相同视频，之后再确认或重新创建本地草稿。','notice small'));if(!accountReady)item.append(element('p','此任务的账号已断开，不能再确认或重试。请连接新账号并创建新的本地草稿。','notice small'));
    const actions=element('div',undefined,'row');if(job.state==='draft'&&actionReady)actions.append(focusControl(focus,button(job.mode==='draft'?'确认上传并保存平台草稿':'确认立即上传投稿',async()=>{const updated=await api('/jobs/'+encodeURIComponent(job.id)+'/confirm',{method:'POST'});pinJob(updated);message('已确认此任务，等待上传器执行。');}),'job:'+job.id+':confirm'));
    if(['draft','queued','running'].includes(job.state))actions.append(focusControl(focus,button('取消',async()=>{const updated=await api('/jobs/'+encodeURIComponent(job.id)+'/cancel',{method:'POST'});pinJob(updated);message('已请求取消。平台已接收的内容不会被撤回。');}),'job:'+job.id+':cancel'));
    if(['failed','canceled','unknown'].includes(job.state)&&actionReady){let acknowledge=null;if(job.state==='unknown'){const label=element('label',undefined,'choice');acknowledge=focusControl(focus,element('input'),'job:'+job.id+':acknowledge');acknowledge.type='checkbox';acknowledge.checked=unknownAcknowledgements.has(job.id);acknowledge.addEventListener('change',()=>{if(acknowledge.checked)unknownAcknowledgements.add(job.id);else unknownAcknowledgements.delete(job.id);});label.append(acknowledge,element('span','我已在平台核对结果，确定需要重新上传'));item.append(label);}actions.append(focusControl(focus,button('重新创建本地草稿',async()=>{if(acknowledge&&!acknowledge.checked)throw new Error('请先到平台核对结果，并勾选确认。');const successor=await api('/jobs/'+encodeURIComponent(job.id)+'/retry',{method:'POST',json:{acknowledge_unknown:!!acknowledge?.checked}});jobToFocus=successor.id;message(successor.state==='draft'?'本地草稿已就绪，已定位到该任务。请核对后再确认。':'未创建新草稿：已有后继任务为“'+(stateNames[successor.state]||successor.state)+'”。已定位到该任务，请查看其当前状态。');}),'job:'+job.id+':retry'));}if(actions.children.length)item.append(actions);$('jobs').append(item);}
  restoreRenderedFocus(focus);
}
function renderEngineStatus(status){const backend=status.backend||{};const state=backend.ready?'ready':backend.state||backend.status||'不可用';let scheduler=status.worker_running?'运行中':'未运行';if(status.scheduler_state==='faulted')scheduler='上传调度故障';if(status.scheduler_code)scheduler+=' · '+codeText(status.scheduler_code);$('engine-status').textContent='引擎：'+(stateNames[state]||state)+(backend.code?' · '+codeText(backend.code):'')+'；上传调度：'+scheduler;$('recover-scheduler').hidden=status.scheduler_state!=='faulted';const age=Number(backend.integrity_age_seconds),ttl=Number(backend.integrity_ttl_seconds),observed=Number.isFinite(age)&&Number.isFinite(ttl)&&ttl>0;$('engine-integrity').hidden=!observed;$('engine-integrity').textContent=observed?'运行环境最近检查：'+Math.max(0,age).toFixed(1)+' 秒前'+(backend.integrity_cached?'（缓存最多 '+ttl+' 秒）':'')+'；开始账号操作或上传前会重新完整校验。':'';}
async function refresh(){if(pollPromise)return pollPromise;pollPromise=(async()=>{const volatile=[];for(const item of [...pinnedJobs.values(),...snapshot.jobs])if(['queued','running'].includes(item.state)&&!volatile.includes(item.id)&&volatile.length<64)volatile.push(item.id);const status=await api('/status');snapshot.status=status;renderEngineStatus(status);const results=await Promise.allSettled([api('/accounts'),api('/sources/page?limit=200'),api('/jobs/page?limit=200'),api('/operations'),api('/storage')]);let {accounts,sources,jobs,operations,storage}=snapshot,failed=results.some(item=>item.status==='rejected');if(results[0].status==='fulfilled')accounts=results[0].value;if(results[1].status==='fulfilled'){const sourcePage=results[1].value;for(const item of sourcePage.items)if(pinnedSources.has(item.id))pinSource(item);sources=mergeFirstPage(sourcePage.items,snapshot.sources,sourceHistoryExpanded);if(!sourceHistoryExpanded)sourceNextCursor=sourcePage.next_cursor;}sources=applyUpdates(sources,[...pinnedSources.values()]);if(results[2].status==='fulfilled'){const jobPage=results[2].value,firstIds=new Set(jobPage.items.map(item=>item.id)),missing=volatile.filter(id=>!firstIds.has(id));let resolved=[];if(missing.length){try{resolved=await api('/jobs/resolve?ids='+encodeURIComponent(missing.join(',')));}catch{failed=true;}}for(const item of jobPage.items)if(pinnedJobs.has(item.id))pinJob(item);for(const item of resolved)pinJob(item);jobs=mergeFirstPage(jobPage.items,snapshot.jobs,jobHistoryExpanded||failed);if(!jobHistoryExpanded)jobNextCursor=jobPage.next_cursor;}jobs=applyUpdates(jobs,[...pinnedJobs.values()]);if(results[3].status==='fulfilled')operations=results[3].value;if(results[4].status==='fulfilled')storage=results[4].value;snapshot={status,accounts,sources,jobs,operations,storage};$('records-status').hidden=!failed;$('records-status').textContent=failed?'账号、视频、任务或媒体占用更新失败；当前保留上次成功读取的内容。恢复本地存储后请刷新。':'';renderAccounts();renderSources();renderJobs();renderStorage();renderLogin();})();try{await pollPromise;}finally{pollPromise=null;}}
function schedulePoll(){if(timer!==null)clearTimeout(timer);timer=pageActive?setTimeout(poll,selectedLogin()&&['queued','running'].includes(selectedLogin().state)?1500:3000):null;}
async function poll(){if(timer!==null)clearTimeout(timer);timer=null;if(!pageActive)return;try{if(!busy)await refresh();}catch(error){message('状态刷新失败：'+error.message,true);}finally{schedulePoll();}}
$('refresh').addEventListener('click',()=>mutate(async()=>{message('状态已刷新。');}));
$('recover-scheduler').addEventListener('click',()=>mutate(async()=>{await api('/recover',{method:'POST'});message('上传调度已恢复。请核对结果不确定的任务，并重新确认等待中的草稿。');}));
$('more-sources').addEventListener('click',()=>mutate(async()=>{if(!sourceNextCursor)return;const page=await api('/sources/page?limit=200&cursor='+encodeURIComponent(sourceNextCursor));snapshot.sources=appendPage(snapshot.sources,page.items);sourceNextCursor=page.next_cursor;sourceHistoryExpanded=true;message('已加载更多已导入视频。');}));
$('more-jobs').addEventListener('click',()=>mutate(async()=>{if(!jobNextCursor)return;const page=await api('/jobs/page?limit=200&cursor='+encodeURIComponent(jobNextCursor));snapshot.jobs=appendPage(snapshot.jobs,page.items);jobNextCursor=page.next_cursor;jobHistoryExpanded=true;message('已加载更早任务。');}));
$('copyright').addEventListener('change',updateMetadata);$('source-id').addEventListener('change',showSource);
$('source-restore-cancel').addEventListener('click',()=>closeSourceRestore());
$('source-restore-form').addEventListener('submit',event=>{event.preventDefault();mutate(async()=>{const source=snapshot.sources.find(item=>item.id===restoreSourceId),file=$('source-restore-file').files[0];if(!source)throw new Error('媒体记录已变化，请刷新后重试。');if(!file)throw new Error('请选择与历史记录完全相同的视频。');if(file.size!==Number(source.size))throw new Error('所选视频大小与历史记录不一致，受管副本没有恢复。');message('正在校验文件大小与 SHA-256 并恢复受管副本…');const updated=await api('/sources/'+encodeURIComponent(source.id)+'/media',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});pinSource(updated);snapshot.sources=applyUpdates(snapshot.sources,[updated]);restoreSourceId=null;$('source-restore-panel').hidden=true;$('source-restore-file').value='';renderSources();$('source-id').value=updated.id;showSource();message('受管副本已恢复；旧任务不会自动执行，仍需手动确认或重试／重建。');});});
$('account-form').addEventListener('submit',event=>{event.preventDefault();mutate(async()=>{const platform=$('account-platform').value;let name=$('account-name').value.trim();if(!name){let count=1;do{name=platformNames[platform]+' 账号 '+count++;}while(snapshot.accounts.some(item=>item.platform===platform&&item.name===name));}const account=await api('/accounts',{method:'POST',json:{platform,name}});$('account-name').value='';await startLogin(account.id);});});
$('source-form').addEventListener('submit',event=>{event.preventDefault();mutate(async()=>{const file=$('source-file').files[0];if(!file)throw new Error('请选择视频。');if(file.size>2147483648)throw new Error('视频超过 2 GiB。');message('正在导入视频，请等待文件校验完成…');const source=await api('/sources?name='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});await refresh();pinSource(source);snapshot.sources=applyUpdates(snapshot.sources,[source]);renderSources();$('source-id').value=source.id;showSource();message('视频已导入。');});});
$('job-form').addEventListener('submit',event=>{event.preventDefault();mutate(async()=>{const accountIds=selectedAccounts();if(!accountIds.length)throw new Error('请选择至少一个账号。');if(!$('source-id').value)throw new Error('请先导入并选择视频。');const selected=snapshot.accounts.filter(item=>accountIds.includes(item.id));const bili=selected.some(item=>item.platform==='bilibili');if(bili&&(!$('category-id').value||!$('copyright').value))throw new Error('Bilibili 必须填写分区 ID 并选择原创或转载。');if(bili&&$('copyright').value==='2'&&!$('source-credit').value.trim())throw new Error('转载必须填写来源。');
  const base={source_id:$('source-id').value,title:$('title').value.trim(),description:$('description').value,tags:$('tags').value.split(/[,，]/).map(item=>item.trim()).filter(Boolean),category_id:bili?Number($('category-id').value):null,copyright:bili?Number($('copyright').value):1,source_credit:$('source-credit').value.trim()};
  const tencentMode=$('tencent-mode').value;const signature=JSON.stringify({...base,accountIds:[...accountIds].sort(),tencentMode});if(!draftSubmission||draftSubmission.signature!==signature)draftSubmission={signature,key:crypto.randomUUID()};
  const created=[];for(const mode of ['publish','draft']){const group=selected.filter(item=>(item.platform==='tencent'?tencentMode:'publish')===mode).map(item=>item.id);if(group.length){const rows=await api('/jobs',{method:'POST',json:{...base,account_ids:group,mode,idempotency_key:draftSubmission.key+'-'+mode}});if(Array.isArray(rows))created.push(...rows);}}
  if(created.length){for(const item of created)pinJob(item);snapshot.jobs=applyUpdates(snapshot.jobs,created);}draftSubmission=null;message('本地草稿已创建。请在下方核对每份内容，再确认执行。');});});
const assetId=new URL(location.href).searchParams.get('asset_id');if(assetId&&/^[0-9a-f-]{36}$/.test(assetId)){$('asset-import').hidden=false;$('import-asset').addEventListener('click',()=>mutate(async()=>{const source=await api('/sources/assets/'+encodeURIComponent(assetId),{method:'POST'});await refresh();pinSource(source);snapshot.sources=applyUpdates(snapshot.sources,[source]);renderSources();$('source-id').value=source.id;showSource();$('asset-import').hidden=true;message('下载成品已导入，原下载文件保持不变。');}));}
window.addEventListener('pagehide',()=>{pageActive=false;schedulePoll();scheduleLoginTick();clearQR();});
window.addEventListener('pageshow',event=>{if(!event.persisted)return;pageActive=true;scheduleLoginTick();return poll();});
(async()=>{try{csrf=(await api('/session')).csrf_token;await refresh();message('选择账号和视频，创建本地草稿后确认执行。');}catch(error){message('上传器连接失败：'+error.message,true);}finally{schedulePoll();}})();
</script></body></html>'''
