from __future__ import annotations

import hashlib
import os
import stat
from pathlib import Path

from . import __version__


_REPARSE_POINT = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0)
_FileSignature = tuple[int, int, int, int, int]
_PayloadEntry = tuple[str, Path, _FileSignature]


class ProductBuildIdentityError(RuntimeError):
    """A privacy-safe build identity failure."""


class ProductBuildDriftError(ProductBuildIdentityError):
    """The package payload changed after this process loaded its code."""


class ProductBuildUnavailableError(ProductBuildIdentityError):
    """The package payload could not be read safely."""


def _file_signature(info: os.stat_result) -> _FileSignature:
    return (
        int(info.st_dev),
        int(info.st_ino),
        int(info.st_mode),
        int(info.st_size),
        int(info.st_mtime_ns),
    )


def _plain_package_root(package_root: Path) -> Path:
    root = Path(os.path.abspath(package_root))
    root_info = root.lstat()
    attributes = getattr(root_info, "st_file_attributes", 0)
    if (
        root.is_symlink()
        or bool(_REPARSE_POINT and attributes & _REPARSE_POINT)
        or not stat.S_ISDIR(root_info.st_mode)
    ):
        raise RuntimeError("product package root must be a plain directory")
    return root.resolve(strict=True)


def _payload_inventory(package_root: Path) -> tuple[_PayloadEntry, ...]:
    files: list[_PayloadEntry] = []
    pending = [package_root]
    while pending:
        directory = pending.pop()
        with os.scandir(directory) as entries:
            for entry in entries:
                path = Path(entry.path)
                info = path.lstat()
                attributes = getattr(info, "st_file_attributes", 0)
                if stat.S_ISLNK(info.st_mode) or bool(
                    _REPARSE_POINT and attributes & _REPARSE_POINT
                ):
                    raise RuntimeError(
                        "product package payload must not contain links"
                    )
                if stat.S_ISDIR(info.st_mode):
                    pending.append(path)
                    continue
                if not stat.S_ISREG(info.st_mode):
                    raise RuntimeError(
                        "product package payload contains a special file"
                    )
                relative = path.relative_to(package_root)
                if "__pycache__" in relative.parts and path.suffix == ".pyc":
                    # PEP 3147 cache bytecode is generated from covered source
                    # and can appear after process start. Sourceless bytecode
                    # outside __pycache__ remains part of the payload.
                    continue
                files.append(
                    (
                        relative.as_posix(),
                        path,
                        _file_signature(info),
                    )
                )
    files.sort(key=lambda item: item[0])
    return tuple(files)


def package_payload_sha256(package_root: Path) -> str:
    """Hash the exact importable package payload used by this process.

    The digest deliberately excludes generated bytecode while covering Python
    modules and bundled data files.  Relative paths and byte lengths are framed
    so different file layouts cannot produce the same stream accidentally.
    """

    package_root = _plain_package_root(package_root)
    inventory = _payload_inventory(package_root)
    if not inventory:
        raise RuntimeError("product package payload is unavailable")

    digest = hashlib.sha256()
    for relative_text, path, expected_signature in inventory:
        resolved = path.resolve(strict=True)
        resolved.relative_to(package_root)
        relative = relative_text.encode("utf-8")
        with resolved.open("rb") as stream:
            before = os.fstat(stream.fileno())
            if (
                not stat.S_ISREG(before.st_mode)
                or _file_signature(before) != expected_signature
            ):
                raise RuntimeError(
                    "product package payload changed while hashing"
                )
            payload = stream.read()
            after = os.fstat(stream.fileno())
        if (
            before.st_size != after.st_size
            or before.st_mtime_ns != after.st_mtime_ns
            or len(payload) != after.st_size
        ):
            raise RuntimeError("product package payload changed while hashing")
        digest.update(len(relative).to_bytes(8, "big"))
        digest.update(relative)
        digest.update(len(payload).to_bytes(8, "big"))
        digest.update(payload)
    final_inventory = _payload_inventory(_plain_package_root(package_root))
    if [
        (relative, signature)
        for relative, _path, signature in final_inventory
    ] != [
        (relative, signature)
        for relative, _path, signature in inventory
    ]:
        raise RuntimeError("product package payload changed while hashing")
    return digest.hexdigest()


def product_build_sha256() -> str:
    """Hash the on-disk package payload."""

    return package_payload_sha256(Path(__file__).resolve().parent)


try:
    _PROCESS_BUILD_SHA256: str | None = product_build_sha256()
except Exception:  # noqa: BLE001 - imports must not leak filesystem details
    _PROCESS_BUILD_SHA256 = None

_PROCESS_PRODUCT_IDENTITY = (
    f"{__version__}+build.sha256.{_PROCESS_BUILD_SHA256}"
    if _PROCESS_BUILD_SHA256 is not None
    else None
)


def current_product_identity() -> str:
    """Return the loaded build identity, failing if its files drifted."""

    if _PROCESS_BUILD_SHA256 is None or _PROCESS_PRODUCT_IDENTITY is None:
        raise ProductBuildUnavailableError(
            "product package payload is unavailable"
        ) from None
    try:
        on_disk_sha256 = product_build_sha256()
    except Exception:  # noqa: BLE001 - sanitize filesystem failures
        raise ProductBuildUnavailableError(
            "product package payload is unavailable"
        ) from None
    if on_disk_sha256 != _PROCESS_BUILD_SHA256:
        raise ProductBuildDriftError("product package payload changed")
    return _PROCESS_PRODUCT_IDENTITY


__all__ = [
    "current_product_identity",
    "package_payload_sha256",
    "ProductBuildIdentityError",
    "ProductBuildDriftError",
    "ProductBuildUnavailableError",
    "product_build_sha256",
]
